name: Build for macOS

on:
  push:
    branches:
      - GHActionsactions

jobs:
  job_test:
    uses: .github/workflows/reusable.yaml

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19  # Replace with your desired Go version

      - name: Build x86
        run: go build -o app 
        
      - name: Build arm64
        run: GOOS=linux GOARCH=arm64 go build -o app_arm64

      - name: Test
        run:  |
              go test -coverprofile=coverage.out  ./... 
              go tool cover -html=coverage.out -o report.html

      - name: Create Artifacts
        run: |
          mkdir artifacts
          mv app artifacts/app
          mv app_arm64 artifacts/app_arm64

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macOS-artifacts
          path: artifacts/
        
      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: report.html
          path: report.html
